$ANSIBLE_VAULT;1.1;AES256
39353133613435363438653864323062626263333261363638636538646662623830363361636435
3735656532323732363538383766356261646239653732330a323066653539363461383966306466
65626336613964663066643132366534623835396535623432663431643165623232383963633636
3931393664383835650a336139303062346630323037373330316236363935306261333565383231
66383165303236643563366532363665316165333539616339373463633864616137323534386261
62323765316138333962336531313161396531333439393931363532633538376539633061396232
30333564363234323435616438386632656633353738613866616663613266393531333062353562
32303463363434633666333963303763643839373237623137623164623137383331316530373238
34363061626533383337316164623063393266346431363866336531356261633562303964393931
33633432626335373337633339653864303063313539386339653562663730393063326331663165
643038373532653632363331373862656538
